// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entry.sql

package db

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entry (
    account_id,
    transfer_id,
    amount
) VALUES (
    $1, $2, $3
)
RETURNING
    id,
    account_id,
    transfer_id,
    amount,
    created_at
`

type CreateEntryParams struct {
	AccountID  int64 `json:"account_id"`
	TransferID int64 `json:"transfer_id"`
	Amount     int64 `json:"amount"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry, arg.AccountID, arg.TransferID, arg.Amount)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransferID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, account_id, transfer_id, amount, created_at
FROM entry
WHERE id = $1
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransferID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
