// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            int64              `json:"id"`
	PublicID      pgtype.UUID        `json:"public_id"`
	Balance       int64              `json:"balance"`
	Currency      string             `json:"currency"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PrimaryUserID int64              `json:"primary_user_id"`
}

type AccountUser struct {
	ID        int64              `json:"id"`
	AccountID int64              `json:"account_id"`
	UserID    int64              `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Entry struct {
	ID         int64              `json:"id"`
	AccountID  int64              `json:"account_id"`
	TransferID int64              `json:"transfer_id"`
	Amount     int64              `json:"amount"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Transfer struct {
	ID            int64              `json:"id"`
	FromAccountID int64              `json:"from_account_id"`
	ToAccountID   int64              `json:"to_account_id"`
	Amount        int64              `json:"amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                int64              `json:"id"`
	PublicID          pgtype.UUID        `json:"public_id"`
	Username          string             `json:"username"`
	HashedPassword    string             `json:"hashed_password"`
	FullName          string             `json:"full_name"`
	Email             string             `json:"email"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
