// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (
    public_id,
    username,
    hashed_password,
    full_name,
    email
) VALUES (
    $1, $2, $3, $4, $5
) 
RETURNING 
    id,
    public_id,
    username,
    full_name,
    email
`

type CreateUserParams struct {
	PublicID       pgtype.UUID `json:"public_id"`
	Username       string      `json:"username"`
	HashedPassword string      `json:"hashed_password"`
	FullName       string      `json:"full_name"`
	Email          string      `json:"email"`
}

type CreateUserRow struct {
	ID       int64       `json:"id"`
	PublicID pgtype.UUID `json:"public_id"`
	Username string      `json:"username"`
	FullName string      `json:"full_name"`
	Email    string      `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.PublicID,
		arg.Username,
		arg.HashedPassword,
		arg.FullName,
		arg.Email,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.FullName,
		&i.Email,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, public_id, username, hashed_password, full_name, email, password_changed_at, created_at, is_email_verified FROM "user"
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.IsEmailVerified,
	)
	return i, err
}

const getUserByPublicID = `-- name: GetUserByPublicID :one
SELECT id, public_id, username, hashed_password, full_name, email, password_changed_at, created_at, is_email_verified FROM "user"
WHERE public_id = $1 LIMIT 1
`

func (q *Queries) GetUserByPublicID(ctx context.Context, publicID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPublicID, publicID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.IsEmailVerified,
	)
	return i, err
}
