// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verify_email.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerifyEmail = `-- name: CreateVerifyEmail :one
INSERT INTO "verify_emails" (
    user_public_id,
    email,
    secret_code
) VALUES (
    $1, $2, $3
) RETURNING id, user_public_id, email, secret_code, is_used, expired_at, created_at
`

type CreateVerifyEmailParams struct {
	UserPublicID pgtype.UUID `json:"user_public_id"`
	Email        string      `json:"email"`
	SecretCode   string      `json:"secret_code"`
}

func (q *Queries) CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error) {
	row := q.db.QueryRow(ctx, createVerifyEmail, arg.UserPublicID, arg.Email, arg.SecretCode)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.UserPublicID,
		&i.Email,
		&i.SecretCode,
		&i.IsUsed,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}
